logging:
  level: INFO
tws_server:
  host: 127.0.0.1
  port: 7497
client:
  stand-alone: 0
  update-conid-db: 1
inputs:
  movements_path: data/movements.csv
  batch: movements_batch
trading_db:
  path: data/trading.db
  schemas: ib_tws_proxy/backing_db/schema
  seed_data: ib_tws_proxy/backing_db/seed-data
  expected_version: 0
  target_version: 1
  version_date: "2024-02-01 00:00:00.000"