cervino:
  app_id: cervino
  batch_prefix: order_batch
  log_file_name: logging.yml
  allocation: C282 # Default value for Cervino

input:
  input_dir: "."
  file_prefix: movements
  file_name: movements.csv
  sheet_name: Movements

output:
  output_dir: "."
  file_prefix: "cervino_command_output"
  file_name: "cervino_command_output.xlsx"  # if provided `file_prefix` is ignored
  inputs_sheet: inputs
  known_sheet: known
  updated_sheet: updated
  missing_sheet: missing
  movement_sheet: movement
  error_sheet: errors

db:
  storage_name: cervino.db
  echo: false


tws:
  port: 7497
  host: 'localhost'
