version: 1

formatters:
  simple:  # Define a formatter named "simple"
    # https://docs.python.org/3/library/logging.html#logrecord-attributes
    format: "[%(threadName)s] %(asctime)s - %(module)s - %(levelname)s - %(message)s"  # Message format string

handlers:
  console:  # Define a handler named "console"
    class: logging.StreamHandler  # Use the StreamHandler class for console output
    level: DEBUG  # Set the minimum logging level for this handler (DEBUG)
    formatter: simple  # Use the "simple" formatter defined above

  all_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/corvino.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  info_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: simple
    filename: /tmp/corvino_info.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  error_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: simple
    filename: /tmp/corvino_errors.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  debug_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: /tmp/corvino_debug.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  critical_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: CRITICAL
    formatter: simple
    filename: /tmp/corvino_critical.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  warn_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: WARNING
    formatter: simple
    filename: /tmp/corvino_warning.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  root:  # Configure the root logger
    level: INFO  # Set the root logger level (DEBUG)
    handlers: [all_file_handler]  # Use the "catch-all" file for the root logger
  ibapi:
    level: WARNING
  salduba.ib_tws_proxy.backing_db.repo:
    level: WARNING
  salduba.ib_tws_proxy.backing_db.db:
    level: WARNING
  salduba.ib_tws_proxy.base_proxy.tws_proxy:
    level: INFO
  salduba.ib_tws_proxy.contracts:
    level: INFO
  salduba.ib_tws_proxy.orders:
    level: DEBUG
  salduba.corvino.services.app:
    level: DEBUG
  salduba.ib_tws_proxy.contracts.lookup_contract_details:
    level: INFO
