-- See https://interactivebrokers.github.io/tws-api/classIBApi_1_1DeltaNeutralContract.html
-- See: https://ibkrcampus.com/ibkr-api-page/twsapi-doc/#contracts
-- See https://interactivebrokers.github.io/tws-api/classIBApi_1_1ComboLeg.html
-- See https://interactivebrokers.github.io/tws-api/classIBApi_1_1TagValue.html
-- See https://interactivebrokers.github.io/tws-api/classIBApi_1_1ContractDetails.html

CREATE TABLE DELTA_NEUTRAL_CONTRACT (
	con_id INTEGER NOT NULL,
	delta FLOAT NOT NULL,
	price FLOAT NOT NULL,
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid)
);


CREATE TABLE SOFT_DOLLAR_TIER (
	name VARCHAR(255) NOT NULL,
	value VARCHAR(255) NOT NULL,
	display_name VARCHAR(255) NOT NULL,
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid)
);

CREATE TABLE ORDER_STATUS (
	order_id INTEGER NOT NULL,
	status VARCHAR(14) NOT NULL,
	filled FLOAT NOT NULL,
	remaining FLOAT NOT NULL,
	avg_fill_price FLOAT NOT NULL,
	perm_id INTEGER NOT NULL,
	parent_id INTEGER,
	last_fill_price FLOAT NOT NULL,
	client_id INTEGER NOT NULL,
	why_held VARCHAR(255) NOT NULL,
	mkt_cap_price FLOAT NOT NULL,
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid)
);

CREATE TABLE CONTRACT (
	expires_on INTEGER,
	con_id INTEGER NOT NULL,
	symbol VARCHAR(255) NOT NULL,
	sec_type VARCHAR(3) NOT NULL,
	last_trade_date_or_contract_month VARCHAR(255),
	strike FLOAT NOT NULL,
	right VARCHAR(255),
	multiplier VARCHAR(255),
	lookup_exchange VARCHAR(8) NOT NULL,
	exchange VARCHAR(8) NOT NULL,
	primary_exchange VARCHAR(8) NOT NULL,
	currency VARCHAR(7) NOT NULL,
	local_symbol VARCHAR(255),
	trading_class VARCHAR(255),
	sec_id_type VARCHAR(255),
	sec_id VARCHAR(255),
	combo_legs_description VARCHAR(255),
	include_expired BOOLEAN NOT NULL,
	delta_neutral_contract_fk VARCHAR(255),
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid),
	FOREIGN KEY(delta_neutral_contract_fk) REFERENCES DELTA_NEUTRAL_CONTRACT (rid)
);



CREATE TABLE ORDER_T (
	orderId INTEGER NOT NULL,
	clientId INTEGER NOT NULL,
	action VARCHAR(255) NOT NULL,
	orderType VARCHAR(255) NOT NULL,
	transmit BOOLEAN NOT NULL,
	permId INTEGER,
	solicited BOOLEAN,
	totalQuantity FLOAT,
	lmtPrice FLOAT,
	auxPrice FLOAT,
	tif VARCHAR(255),
	ocaGroup VARCHAR(255),
	ocaType INTEGER,
	orderRef VARCHAR(255),
	parentId INTEGER,
	blockOrder BOOLEAN,
	sweepToFill BOOLEAN,
	displaySize INTEGER,
	triggerMethod INTEGER,
	outsideRth BOOLEAN,
	hidden BOOLEAN,
	goodAfterTime VARCHAR(255),
	goodTillDate VARCHAR(255),
	overridePercentageConstraints BOOLEAN,
	rule80A VARCHAR(255),
	allOrNone BOOLEAN,
	minQty INTEGER,
	percentOffset FLOAT,
	trailStopPrice FLOAT,
	trailingPercent FLOAT,
	faGroup VARCHAR(255),
	faMethod VARCHAR(255),
	faPercentage VARCHAR(255),
	openClose VARCHAR(255),
	origin INTEGER,
	shortSaleSlot INTEGER,
	designatedLocation VARCHAR(255),
	exemptCode INTEGER,
	discretionaryAmt FLOAT,
	optOutSmartRouting BOOLEAN,
	auctionStrategy INTEGER,
	startingPrice FLOAT,
	stockRefPrice FLOAT,
	delta FLOAT,
	stockRangeLower FLOAT,
	stockRangeUpper FLOAT,
	volatility FLOAT,
	volatilityType INTEGER,
	continuousUpdate INTEGER,
	referencePriceType INTEGER,
	deltaNeutralOrderType VARCHAR(255),
	deltaNeutralAuxPrice FLOAT,
	deltaNeutralConId INTEGER,
	deltaNeutralSettlingFirm VARCHAR(255),
	deltaNeutralClearingAccount VARCHAR(255),
	deltaNeutralOpenClose VARCHAR(255),
	deltaNeutralShortSale VARCHAR(255),
	deltaNeutralShortSaleSlot VARCHAR(255),
	deltaNeutralDesignatedLocation VARCHAR(255),
	basisPoints FLOAT,
	basisPointsType INTEGER,
	scaleInitLevelSize INTEGER,
	scaleSubsLevelSize INTEGER,
	scalePriceIncrement FLOAT,
	scalePriceAdjustValue FLOAT,
	scalePriceAdjustInterval INTEGER,
	scaleProfitOffset FLOAT,
	scaleAutoReset BOOLEAN,
	scaleInitPosition INTEGER,
	scaleInitFillQty INTEGER,
	scaleRandomPercent BOOLEAN,
	hedgeType VARCHAR(255),
	hedgeParam VARCHAR(255),
	account VARCHAR(255),
	settlingFirm VARCHAR(255),
	clearingAccount VARCHAR(255),
	clearingIntent VARCHAR(255),
	algoStrategy VARCHAR(255),
	whatIf BOOLEAN,
	algoId VARCHAR(255),
	notHeld BOOLEAN,
	activeStartTime VARCHAR(255),
	activeStopTime VARCHAR(255),
	scaleTable VARCHAR(255),
	modelCode VARCHAR(255),
	extOperator VARCHAR(255),
	cashQty FLOAT,
	mifid2DecisionMaker VARCHAR(255),
	mifid2DecisionAlgo VARCHAR(255),
	mifid2ExecutionTrader VARCHAR(255),
	mifid2ExecutionAlgo VARCHAR(255),
	dontUseAutoPriceForHedge BOOLEAN,
	autoCancelDate VARCHAR(255),
	filledQuantity FLOAT,
	refFuturesConId INTEGER,
	autoCancelParent BOOLEAN,
	shareholder VARCHAR(255),
	imbalanceOnly BOOLEAN,
	routeMarketableToBbo BOOLEAN,
	parentPermId INTEGER,
	randomizeSize BOOLEAN,
	randomizePrice BOOLEAN,
	referenceContractId INTEGER,
	isPeggedChangeAmountDecrease BOOLEAN,
	peggedChangeAmount FLOAT,
	referenceChangeAmount FLOAT,
	adjustedOrderType VARCHAR(255),
	triggerPrice FLOAT,
	lmtPriceOffset FLOAT,
	adjustedStopPrice FLOAT,
	conditionsIgnoreRth BOOLEAN,
	conditionsCancelOrder BOOLEAN,
	isOmsContainer BOOLEAN,
	usePriceMgmtAlgo BOOLEAN,
	soft_dollar_tier_fk VARCHAR(255),
	order_status_fk VARCHAR(255) NOT NULL,
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid),
	FOREIGN KEY(soft_dollar_tier_fk) REFERENCES SOFT_DOLLAR_TIER (rid),
	FOREIGN KEY(order_status_fk) REFERENCES ORDER_STATUS (rid)
);



CREATE TABLE MOVEMENT (
	status VARCHAR(11) NOT NULL,
	batch VARCHAR(255) NOT NULL,
	ticker VARCHAR(255) NOT NULL,
	trade INTEGER NOT NULL,
	nombre VARCHAR(255) NOT NULL,
	symbol VARCHAR(255) NOT NULL,
	raw_type VARCHAR(255) NOT NULL,
	ibk_type VARCHAR(3) NOT NULL,
	country VARCHAR(2) NOT NULL,
	currency VARCHAR(7) NOT NULL,
	exchange VARCHAR(8) NOT NULL,
	exchange2 VARCHAR(8),
	contract_fk VARCHAR(255) NOT NULL,
	order_fk VARCHAR(255) NOT NULL,
	rid VARCHAR(255) NOT NULL,
	at INTEGER NOT NULL,
	PRIMARY KEY (rid),
	FOREIGN KEY(contract_fk) REFERENCES CONTRACT (rid),
	FOREIGN KEY(order_fk) REFERENCES ORDER_T (rid)
);
